import {
  ACTION_SIZE,
  BODY_PADDING_BOTTOM,
  BODY_PADDING_H,
  DESC_SIZE,
  ICON_GAP,
  ICON_SIZE,
  PH,
  PILL_PADDING_H,
  TITLE_SIZE,
} from "@/constants";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  toastOuter: { position: "absolute", left: 0, right: 0, alignItems: "center" },
  toasterContainer: { zIndex: 9999 },
  toasterLeft: { left: 0, right: 0, alignItems: "flex-start" },
  toasterCenter: { left: 0, right: 0, alignItems: "center" },
  toasterRight: { left: 0, right: 0, alignItems: "flex-end" },
  toasterStack: { width: "100%" },
  anchorTop: { top: 0 },
  anchorBottom: { bottom: 0 },
  pressable: { overflow: "visible" },
  surfaceShell: { position: "relative", overflow: "visible" },
  surfaceShadow: {
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 10,
  },
  clipContainer: {
    overflow: "hidden",
    borderRadius: PH / 2,
    alignItems: "center",
  },
  clipFill: { width: "100%", height: "100%" },
  flipX: { transform: [{ scaleX: -1 }] },
  surfaceCanvas: { position: "relative" },
  svgBg: { position: "absolute", top: 0, left: 0 },
  content: { minHeight: PH },
  header: {
    height: PH,
    paddingHorizontal: PILL_PADDING_H,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
  },
  headerCentered: { alignSelf: "center" },
  headerRight: { alignSelf: "flex-end" },
  iconWrap: {
    width: ICON_SIZE,
    height: ICON_SIZE,
    marginRight: ICON_GAP,
    alignItems: "center",
    justifyContent: "center",
  },
  titleText: {
    fontSize: TITLE_SIZE,
    fontWeight: "700",
    flexShrink: 1,
    textAlign: "left",
  },
  body: {
    paddingHorizontal: BODY_PADDING_H,
    paddingTop: 6,
    paddingBottom: BODY_PADDING_BOTTOM,
  },
  descRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    width: "100%",
  },
  descTextWrap: { flex: 1, minWidth: 0 },
  descText: {
    fontSize: DESC_SIZE,
    lineHeight: DESC_SIZE * 1.55,
    color: "#1f2937",
    textAlign: "left",
  },
  descMeta: {
    color: "#64748b",
    fontSize: 12,
    minWidth: 82,
    paddingTop: 2,
    textAlign: "right",
  },
  descMetaInline: { color: "#64748b", fontSize: 12, marginTop: 6 },
  descWithAction: { marginBottom: 12 },
  textLeft: { textAlign: "left" },
  textCenter: { textAlign: "center" },
  textRight: { textAlign: "right" },
  actionWrap: { marginTop: 0 },
  actionWrapCenter: { alignItems: "center" },
  actionWrapRight: { alignItems: "flex-end" },
  actionBtn: {
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  actionLabel: { fontSize: ACTION_SIZE, fontWeight: "700" },
  inlineProgressTrack: {
    marginTop: 12,
    height: 3,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: "rgba(15,23,42,0.06)",
  },
  inlineProgressFill: {
    width: "100%",
    height: "100%",
    transformOrigin: "left center",
    borderRadius: 999,
  },
  progressTrack: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 3,
    overflow: "hidden",
    backgroundColor: "rgba(0,0,0,0.05)",
  },
  progressFill: {
    width: "100%",
    height: "100%",
    transformOrigin: "left center",
  },
  measureLayer: { position: "absolute", opacity: 0, zIndex: -1 },
  measureCard: { alignSelf: "flex-start" },
  measureHeader: {
    minHeight: PH,
    paddingHorizontal: PILL_PADDING_H,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
  },
  measureBody: {
    paddingHorizontal: BODY_PADDING_H,
    paddingTop: 6,
    paddingBottom: BODY_PADDING_BOTTOM,
  },
  measureInlineProgress: { marginTop: 12, height: 3, borderRadius: 999 },
});

export default styles;
